services:
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/WalkOnTheRight/n8n
    branch: master
    dockerfilePath: docker/images/n8n/Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: yourusername
      - key: N8N_BASIC_AUTH_PASSWORD
        value: yourpassword
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 3000
      - key: WEBHOOK_TUNNEL_URL
        value: https://n8n-bot-aar1.onrender.com
